version: "3.3"

services:

  tristans-app-server:
    build: ./
    ports:
      - '3000:80'
    depends_on:
      - db

  tristans-app-server-stage:
    build: ./
    environment:
      - NODE_ENV=development
    ports:
      - '3000:80'
    depends_on:
      - db

  tristans-app-server-dev:
    build: ./
    environment:
      - NODE_PATH=./src
      - NODE_ENV=development
    command: npx nodemon
    ports:
      - '3000:80'
    volumes:
      - ./src:/var/app/src
    depends_on:
      - db

  tristans-app-server-test:
    build: ./
    environment:
      - NODE_PATH=./src
      - NODE_ENV=development
    command: npx ts-node node_modules/jasmine/bin/jasmine
    volumes:
      - ./src:/var/app/src
    depends_on:
      - db_test

  db_test:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'tristans_app'
      MYSQL_ROOT_PASSWORD: 'xxx'
    expose:
      - '3306'
    volumes:
      - ./data_test:/var/lib/mysql

  db:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'tristans_app'
      MYSQL_ROOT_PASSWORD: 'xxx'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql
