version: '3'
services:
  meme-app:
    container_name: meme-app
    restart: always
    build: ./
    ports:
      - '3000:3000'

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - meme-app